Repository nilearn/nilearn, pull requests merged in 2021-01, with the labels that each got.

#2643 Add cbar_tick_format arg to plot_surf
  doc/whats_new.rst
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Enhancement

#2650 drop Python 3.5 in release 0.8.0
  nilearn/__init__.py
Labels: Maintenance

#2663 Deprecate numpy arrays and bytes in datasets module
  nilearn/datasets/__init__.py
Labels: Datasets, Maintenance

#2332 Allow markers only in their respective hemisphere when appropriate
  nilearn/plotting/displays.py
  nilearn/plotting/tests/test_img_plotting.py
Labels: Need Review

#2474 changing surface mesh from a list to a namedtuple
  nilearn/plotting/surf_plotting.py
  nilearn/surface/__init__.py
  nilearn/surface/surface.py
  nilearn/surface/tests/test_surface.py
Labels: Need Review
