Repository nilearn/nilearn, pull requests merged in 2022-08, with the labels that each got.

#3311 [ENH] Add n_elements_ attribute to masker classes
  doc/changes/latest.rst
  nilearn/maskers/base_masker.py
  nilearn/maskers/multi_nifti_masker.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/maskers/tests/test_multi_nifti_masker.py
  nilearn/maskers/tests/test_nifti_labels_masker.py
  nilearn/maskers/tests/test_nifti_maps_masker.py
  nilearn/maskers/tests/test_nifti_masker.py
  nilearn/maskers/tests/test_nifti_spheres_masker.py
  nilearn/masking.py
Labels: Enhancement

#3328 update vol_to_surf docstring
  nilearn/surface/surface.py
Labels: Documentation

#3314 [DOC] Document additional analysis designs for non-parametric methods
  doc/glm/second_level_model.rst
  examples/05_glm_second_level/plot_second_level_one_sample_test.py
  examples/07_advanced/plot_localizer_mass_univariate_methods.py
  nilearn/glm/second_level/second_level.py
Labels: Documentation, GLM
