Repository nilearn/nilearn, pull requests merged in 2023-03, with the labels that each got.

#3549 [FMT] format example/00_tutorials
  examples/00_tutorials/plot_3d_and_4d_niimg.py
  examples/00_tutorials/plot_decoding_tutorial.py
  examples/00_tutorials/plot_nilearn_101.py
  examples/00_tutorials/plot_python_101.py
  examples/00_tutorials/plot_single_subject_single_run.py
  examples/01_plotting/plot_carpet.py
  examples/01_plotting/plot_demo_plotting.py
  examples/01_plotting/plot_haxby_masks.py
Labels: Documentation, code quality, Maintenance

#3555 [FMT] format example/06_manipulating_images
  examples/06_manipulating_images/plot_affine_transformation.py
  examples/06_manipulating_images/plot_compare_mean_image.py
  examples/06_manipulating_images/plot_extract_regions_labels_image.py
  examples/06_manipulating_images/plot_extract_rois_smith_atlas.py
  examples/06_manipulating_images/plot_extract_rois_statistical_maps.py
  examples/06_manipulating_images/plot_mask_computation.py
  examples/06_manipulating_images/plot_negate_image.py
  examples/06_manipulating_images/plot_nifti_labels_simple.py
  examples/06_manipulating_images/plot_nifti_simple.py
  examples/06_manipulating_images/plot_resample_to_template.py
  examples/06_manipulating_images/plot_roi_extraction.py
  examples/06_manipulating_images/plot_smooth_mean_image.py
Labels: Documentation, code quality, Maintenance

#3554 [FMT] format example/05_glm_second_level
  examples/05_glm_second_level/plot_oasis.py
  examples/05_glm_second_level/plot_proportion_activated_voxels.py
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/05_glm_second_level/plot_second_level_design_matrix.py
  examples/05_glm_second_level/plot_second_level_one_sample_test.py
  examples/05_glm_second_level/plot_second_level_two_sample_test.py
  examples/05_glm_second_level/plot_thresholding.py
Labels: Documentation, code quality, Maintenance

#3553 [FMT] format example/04_glm_first_level
  examples/04_glm_first_level/plot_adhd_dmn.py
  examples/04_glm_first_level/plot_bids_features.py
  examples/04_glm_first_level/plot_design_matrix.py
  examples/04_glm_first_level/plot_fiac_analysis.py
  examples/04_glm_first_level/plot_fir_model.py
  examples/04_glm_first_level/plot_first_level_details.py
  examples/04_glm_first_level/plot_fixed_effects.py
  examples/04_glm_first_level/plot_hrf.py
  examples/04_glm_first_level/plot_localizer_surface_analysis.py
  examples/04_glm_first_level/plot_predictions_residuals.py
  examples/04_glm_first_level/plot_spm_multimodal_faces.py
  examples/04_glm_first_level/plot_write_events_file.py
Labels: Documentation, code quality, Maintenance

#3551 [FMT] format example/02_decoding
  examples/02_decoding/plot_haxby_anova_svm.py
  examples/02_decoding/plot_haxby_different_estimators.py
  examples/02_decoding/plot_haxby_frem.py
  examples/02_decoding/plot_haxby_full_analysis.py
  examples/02_decoding/plot_haxby_glm_decoding.py
  examples/02_decoding/plot_haxby_grid_search.py
  examples/02_decoding/plot_haxby_multiclass.py
  examples/02_decoding/plot_haxby_searchlight.py
  examples/02_decoding/plot_haxby_searchlight_surface.py
  examples/02_decoding/plot_haxby_stimuli.py
  examples/02_decoding/plot_mixed_gambles_frem.py
  examples/02_decoding/plot_miyawaki_encoding.py
  examples/02_decoding/plot_miyawaki_reconstruction.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/02_decoding/plot_oasis_vbm_space_net.py
  examples/02_decoding/plot_simulated_data.py
Labels: Documentation, code quality, Maintenance

#3552 [FMT] format example/03_connectivity
  examples/03_connectivity/plot_atlas_comparison.py
  examples/03_connectivity/plot_compare_decomposition.py
  examples/03_connectivity/plot_data_driven_parcellations.py
  examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
  examples/03_connectivity/plot_group_level_connectivity.py
  examples/03_connectivity/plot_inverse_covariance_connectome.py
  examples/03_connectivity/plot_multi_subject_connectome.py
  examples/03_connectivity/plot_probabilistic_atlas_extraction.py
  examples/03_connectivity/plot_seed_to_voxel_correlation.py
  examples/03_connectivity/plot_signal_extraction.py
  examples/03_connectivity/plot_simulated_connectome.py
  examples/03_connectivity/plot_sphere_based_connectome.py
Labels: Documentation, code quality, Maintenance

#3548 [FMT] format image module
  .github/workflows/auto-comment.yml
  .github/workflows/flake8.yml
  .github/workflows/isort.yml
  .github/workflows/update_precommit_hooks.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  examples/masker_note.rst
  maint_tools/show-python-packages-versions.py
  nilearn/image/__init__.py
  nilearn/image/image.py
  nilearn/image/resampling.py
  nilearn/image/tests/test_image.py
  nilearn/image/tests/test_resampling.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: Documentation, code quality, Maintenance

#3173 Allow not scaling background maps for surface plots
  doc/changes/latest.rst
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  nilearn/_utils/docs.py
  nilearn/plotting/html_surface.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_html_surface.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Documentation, Plotting

#3362 [FIX] Change calculation of TR in glm.first_level.hemodynamic_models.compute_regressor()
  doc/changes/latest.rst
  doc/changes/names.rst
  nilearn/glm/first_level/hemodynamic_models.py
  nilearn/glm/tests/test_hemodynamic_models.py
Labels: GLM

#3525 [FIX] extend supported BIDS entities
  .gitignore
  doc/changes/latest.rst
  nilearn/_utils/data_gen.py
  nilearn/_utils/tests/test_data_gen.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_second_level.py
  nilearn/interfaces/bids/_utils.py
Labels: GLM
