Repository nilearn/nilearn, pull requests merged in 2024-12, with the labels that each got.

#4836 [FIX] rework plot_surf_atlas example
  examples/01_plotting/plot_surf_atlas.py
Labels: Documentation, Surface, Review required

#4841 [FIX] update plot_surface_bids_analysis
  examples/07_advanced/plot_surface_bids_analysis.py
Labels: Documentation, Surface, Review required

#4837 [FIX] update plot_3d_map_to_surface_projection
  examples/01_plotting/plot_3d_map_to_surface_projection.py
Labels: Documentation, Surface, Review required

#4838 [FIX] update plot_surf_stat_map to properly use surface api
  examples/01_plotting/plot_surf_stat_map.py
Labels: Documentation, Surface, Review required

#4834 [FIX] update plot_surface_101 example
  examples/00_tutorials/plot_surface_101.py
Labels: Documentation, Surface, Review required

#4835 [FIX] update plot_surface_image_and_maskers.py
  examples/07_advanced/plot_surface_image_and_maskers.py
Labels: Documentation, Surface, Review required

#4840 [FIX] update plot_localizer_surface_analysis
  examples/04_glm_first_level/plot_localizer_surface_analysis.py
Labels: Documentation, Surface, Review required

#4846 [REF] use underscore for unused variable in loop
  nilearn/plotting/tests/test_html_document.py
Labels: Code quality

#4845 [REF] simplify empty collection comparison
  nilearn/datasets/_utils.py
  nilearn/datasets/tests/test_utils.py
Labels: Code quality

#4844 [REF] use join
  nilearn/_utils/masker_validation.py
Labels: Code quality

#4843 [REF] avoid `not any()` or `not all()`
  nilearn/interfaces/tests/test_bids.py
  nilearn/plotting/displays/_figures.py
Labels: Code quality

#4833 [REF] use dict comprehension
  nilearn/glm/first_level/first_level.py
  nilearn/maskers/_utils.py
  nilearn/plotting/cm.py
  nilearn/plotting/find_cuts.py
Labels: Code quality

#4826 [REF] refactor unnecessary else block
  nilearn/_utils/niimg.py
  nilearn/_utils/niimg_conversions.py
  nilearn/_utils/testing.py
  nilearn/conftest.py
  nilearn/datasets/tests/test_func.py
  nilearn/image/image.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/surf_plotting.py
Labels: Code quality

#4822 [REF] apply sourcery suggestions to use comprehension
  nilearn/_utils/segmentation.py
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/image/resampling.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/js_plotting_utils.py
Labels: Code quality

#4819 [REF] apply use-fstring suggested by sourcery
  examples/02_decoding/plot_miyawaki_encoding.py
  nilearn/_utils/cache_mixin.py
  nilearn/_utils/testing.py
Labels: Code quality

#4825 [REF] remove redundant slice index
  examples/02_decoding/plot_haxby_understand_decoder.py
  nilearn/glm/tests/test_second_level.py
  nilearn/image/tests/test_image.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/html_stat_map.py
  nilearn/tests/test_signal.py
Labels: Code quality

#4823 [REF] move assign variable within the if block where they are needed
  nilearn/_utils/niimg.py
  nilearn/_utils/testing.py
  nilearn/image/resampling.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/plotting/matrix_plotting.py
Labels: Code quality

#4831 [REF] Apply de Morgan's law for conditional
  nilearn/decoding/space_net.py
  nilearn/image/resampling.py
  nilearn/plotting/displays/_figures.py
  nilearn/tests/test_signal.py
Labels: Code quality

#4818 [STY] run style checks on doc
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.rst
  doc/bibliography.rst
  doc/building_blocks/manual_pipeline.rst
  doc/building_blocks/neurovault.rst
  doc/connectivity/connectome_extraction.rst
  doc/connectivity/functional_connectomes.rst
  doc/connectivity/region_extraction.rst
  doc/decoding/decoding_intro.rst
  doc/decoding/frem.rst
  doc/decoding/going_further.rst
  doc/decoding/searchlight.rst
  doc/decoding/space_net.rst
  doc/glm/first_level_model.rst
  doc/glm/glm_intro.rst
  doc/glm/second_level_model.rst
  doc/introduction.rst
  doc/maintenance.rst
  doc/manipulating_images/input_output.rst
  doc/plotting/index.rst
  nilearn/datasets/description/aal.rst
  nilearn/datasets/description/basc_multiscale_2015.rst
  nilearn/datasets/description/juelich.rst
  nilearn/datasets/description/miyawaki2008.rst
  nilearn/datasets/description/seitzman_2018.rst
  pyproject.toml
Labels: Code quality

#4832 [REF] use get item where possible
  nilearn/plotting/tests/test_js_plotting_utils.py
Labels: Code quality

#4847 [DOC] use higher contrast pygment style for dark mode
  doc/conf.py
Labels: Documentation, User Experience

#4827 [REF] use list extend instead of append
  nilearn/_utils/data_gen.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/displays/_figures.py
Labels: Code quality

#4824 [REF] simplify assignement
  nilearn/_utils/docs.py
  nilearn/_utils/segmentation.py
  nilearn/_utils/tests/test_segmentation.py
  nilearn/decoding/space_net_solvers.py
  nilearn/glm/contrasts.py
  nilearn/interfaces/fmriprep/load_confounds_components.py
  nilearn/maskers/_utils.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/html_connectome.py
  nilearn/plotting/html_surface.py
Labels: Code quality

#4807 [FIX][ENH][DOC] allow events and design matrices inputs to be pathlike
  doc/changes/latest.rst
  doc/modules/plotting.rst
  nilearn/_utils/glm.py
  nilearn/_utils/tests/test_glm.py
  nilearn/glm/_base.py
  nilearn/glm/first_level/design_matrix.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/second_level/second_level.py
  nilearn/glm/tests/test_design_matrix.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_second_level.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/tests/test_matrix_plotting.py
Labels: Review required

#4911 [FIX] Properly set number fo permutation chunks when n_jobs > n_perm
  .github/workflows/build-docs.yml
  doc/conf.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/07_advanced/plot_haxby_mass_univariate.py
  nilearn/mass_univariate/permuted_least_squares.py
  nilearn/mass_univariate/tests/test_permuted_least_squares.py
  pyproject.toml
  tox.ini
Labels: Blocker

#4287 [DOC] Add comparison of meaning differences of GLM between different libraries
  CITATION.cff
  doc/changes/latest.rst
  doc/glm/glm_intro.rst
  doc/glm/index.rst
  doc/glm/meaning_difference.rst
  doc/modules/generated_reports/glm_reports_examples.rst
Labels: Review required

#4830 [ENH] Implement surface maps masker
  doc/changes/latest.rst
  doc/modules/maskers.rst
  nilearn/_utils/tests/test_common.py
  nilearn/maskers/__init__.py
  nilearn/maskers/_utils.py
  nilearn/maskers/surface_maps_masker.py
  nilearn/maskers/tests/test_surface_maps_masker.py
Labels: Blocker, Surface

#4962 [FIX] Change link to TFCE tutorial
  doc/glossary.rst
Labels: Documentation

#4756 [ENH] Allow `Parcellations` to work with Surface API
  doc/changes/latest.rst
  nilearn/_utils/tests/test_common.py
  nilearn/decomposition/_base.py
  nilearn/maskers/surface_labels_masker.py
  nilearn/regions/parcellations.py
  nilearn/regions/tests/test_parcellations.py
Labels: Surface

#4959 [ENH] update default colors
  doc/changes/latest.rst
  doc/manipulating_images/masker_objects.rst
  examples/00_tutorials/plot_3d_and_4d_niimg.py
  examples/00_tutorials/plot_decoding_tutorial.py
  examples/00_tutorials/plot_single_subject_single_run.py
  examples/01_plotting/plot_carpet.py
  examples/01_plotting/plot_demo_glass_brain_extensive.py
  examples/01_plotting/plot_dim_plotting.py
  examples/01_plotting/plot_overlay.py
  examples/01_plotting/plot_surf_atlas.py
  examples/01_plotting/plot_surf_stat_map.py
  examples/02_decoding/plot_haxby_frem.py
  examples/02_decoding/plot_haxby_full_analysis.py
  examples/02_decoding/plot_haxby_glm_decoding.py
  examples/02_decoding/plot_haxby_multiclass.py
  examples/02_decoding/plot_haxby_searchlight.py
  examples/02_decoding/plot_haxby_searchlight_surface.py
  examples/02_decoding/plot_haxby_stimuli.py
  examples/02_decoding/plot_mixed_gambles_frem.py
  examples/02_decoding/plot_miyawaki_encoding.py
  examples/02_decoding/plot_miyawaki_reconstruction.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/02_decoding/plot_oasis_vbm_space_net.py
  examples/02_decoding/plot_simulated_data.py
  examples/03_connectivity/plot_compare_decomposition.py
  examples/03_connectivity/plot_data_driven_parcellations.py
  examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
  examples/03_connectivity/plot_group_level_connectivity.py
  examples/03_connectivity/plot_multi_subject_connectome.py
  examples/03_connectivity/plot_seed_to_voxel_correlation.py
  examples/03_connectivity/plot_sphere_based_connectome.py
  examples/04_glm_first_level/plot_predictions_residuals.py
  examples/04_glm_first_level/plot_spm_multimodal_faces.py
  examples/04_glm_first_level/plot_two_runs_model.py
  examples/04_glm_first_level/plot_write_events_file.py
  examples/05_glm_second_level/plot_proportion_activated_voxels.py
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/05_glm_second_level/plot_second_level_one_sample_test.py
  examples/06_manipulating_images/plot_extract_rois_smith_atlas.py
  examples/06_manipulating_images/plot_roi_extraction.py
  examples/07_advanced/plot_advanced_decoding_scikit.py
  examples/07_advanced/plot_age_group_prediction_cross_val.py
  examples/07_advanced/plot_beta_series.py
  examples/07_advanced/plot_bids_analysis.py
  examples/07_advanced/plot_haxby_mass_univariate.py
  examples/07_advanced/plot_localizer_mass_univariate_methods.py
  examples/07_advanced/plot_localizer_simple_analysis.py
  examples/07_advanced/plot_neurovault_meta_analysis.py
  examples/07_advanced/plot_surface_bids_analysis.py
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/plotting/html_stat_map.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_img_plotting/test_plot_glass_brain.py
  nilearn/reporting/glm_reporter.py
Labels: Review required

#5004 [MAINT] Remove legacy format for dataset fetchers
  doc/changes/latest.rst
  doc/get_data_examples.py
  doc/visual_testing/reporter_visual_inspection_suite.py
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  examples/01_plotting/plot_dim_plotting.py
  examples/01_plotting/plot_prob_atlas.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/02_decoding/plot_oasis_vbm_space_net.py
  examples/03_connectivity/plot_atlas_comparison.py
  examples/03_connectivity/plot_sphere_based_connectome.py
  examples/05_glm_second_level/plot_oasis.py
  examples/05_glm_second_level/plot_proportion_activated_voxels.py
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/05_glm_second_level/plot_second_level_one_sample_test.py
  examples/05_glm_second_level/plot_second_level_two_sample_test.py
  examples/05_glm_second_level/plot_thresholding.py
  examples/07_advanced/plot_localizer_mass_univariate_methods.py
  examples/07_advanced/plot_localizer_simple_analysis.py
  nilearn/_utils/docs.py
  nilearn/conftest.py
  nilearn/datasets/atlas.py
  nilearn/datasets/func.py
  nilearn/datasets/struct.py
  nilearn/datasets/tests/test_func.py
  nilearn/datasets/tests/test_struct.py
Labels: Blocker, Review required
