Repository nilearn/nilearn, pull requests merged in 2024-11, with the labels that each got.

#4547 [MAINT] check estimators compliance with the scikit-learn recommendations
  nilearn/_utils/class_inspect.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/connectome/tests/test_group_sparse_cov.py
  nilearn/decoding/searchlight.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/decoding/tests/test_searchlight.py
  nilearn/decomposition/_base.py
  nilearn/decomposition/tests/test_base.py
  nilearn/experimental/surface/maskers.py
  nilearn/glm/_base.py
  nilearn/glm/tests/test_second_level.py
  nilearn/maskers/base_masker.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/maskers/tests/test_base_masker.py
  nilearn/maskers/tests/test_multi_nifti_labels_masker.py
  nilearn/maskers/tests/test_multi_nifti_maps_masker.py
  nilearn/maskers/tests/test_multi_nifti_masker.py
  nilearn/maskers/tests/test_nifti_spheres_masker.py
  nilearn/regions/hierarchical_kmeans_clustering.py
  nilearn/regions/rena_clustering.py
  nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
  nilearn/regions/tests/test_rena_clustering.py
Labels: Code quality

#4658 [REF] use path for resolve globbing
  nilearn/_utils/niimg_conversions.py
  nilearn/_utils/path_finding.py
  nilearn/_utils/tests/test_helpers.py
  nilearn/_utils/tests/test_path_finding.py
  nilearn/decomposition/_base.py
  nilearn/decomposition/tests/test_canica.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
  nilearn/maskers/multi_nifti_masker.py
  nilearn/surface/surface.py
Labels: Code quality, Review required

#4684 [DOC] move example for surface API plot_surface_image_and_maskers
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/plotting/_utils.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Surface, Review required

#4713 [ENH] Add plotting contours using SurfaceImage with plotly
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  examples/01_plotting/plot_surf_atlas.py
  examples/01_plotting/plot_surf_stat_map.py
  nilearn/plotting/displays/_figures.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Surface

#4711 [DOC] Use SurfaceImage object for the Searchlight surface example
  examples/02_decoding/plot_haxby_searchlight.py
  examples/02_decoding/plot_haxby_searchlight_surface.py
  nilearn/decoding/searchlight.py
Labels: Surface

#4610 [ENH] Handling of SurfaceData in compute_contrast
  nilearn/glm/contrasts.py
  nilearn/glm/tests/test_first_level.py
Labels: Surface

#4577 [ENH] Allow to run clustering on SurfaceImage
  doc/changes/latest.rst
  nilearn/decoding/tests/test_decoder.py
  nilearn/decomposition/_base.py
  nilearn/regions/rena_clustering.py
  nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
  nilearn/regions/tests/test_parcellations.py
  nilearn/regions/tests/test_rena_clustering.py
Labels: Enhancement, Surface

#4719 [ENH] run fit and transform of SurfaceMasker on list of Surface images
  doc/changes/latest.rst
  nilearn/maskers/_utils.py
  nilearn/maskers/surface_masker.py
  nilearn/maskers/tests/test_surface_masker.py
  nilearn/maskers/tests/test_utils.py
  nilearn/surface/surface.py
  pyproject.toml
  tox.ini
Labels: Surface, Review required

#4740 [STY] Appending to dictionary following its definition
  nilearn/datasets/atlas.py
  nilearn/plotting/cm.py
Labels: Code quality

#4749 [MAINT] Special method should return `NotImplemented`
  nilearn/datasets/neurovault.py
Labels: Code quality

#4733 [STY] Explicit exception raised in the assert message
  nilearn/glm/first_level/design_matrix.py
  nilearn/plotting/cm.py
Labels: Code quality

#4771 [FIX] Force the parts of PolyData to be 2D
  doc/visual_testing/reporter_visual_inspection_suite.py
  examples/01_plotting/plot_surf_atlas.py
  examples/01_plotting/plot_surf_stat_map.py
  examples/08_experimental/README.rst
  nilearn/datasets/struct.py
  nilearn/glm/tests/test_first_level.py
  nilearn/maskers/_utils.py
  nilearn/maskers/surface_labels_masker.py
  nilearn/maskers/surface_masker.py
  nilearn/maskers/tests/test_surface_labels_masker.py
  nilearn/maskers/tests/test_surface_masker.py
  nilearn/maskers/tests/test_utils.py
  nilearn/plotting/_utils.py
  nilearn/plotting/displays/_figures.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/regions/rena_clustering.py
  nilearn/regions/tests/test_rena_clustering.py
  nilearn/surface/surface.py
  nilearn/surface/tests/test_surface.py
Labels: Surface

#4743 [MAINT] Sequence value overwritten unconditionally
  nilearn/datasets/atlas.py
Labels: Code quality

#4770 [ENH] Allow SurfaceLabelsMasker to work with a list of Surface images
  nilearn/maskers/surface_labels_masker.py
  nilearn/maskers/tests/test_surface_labels_masker.py
Labels: Surface, Masker

#4753 [MAINT] Disable ruff rules conflicting with the formatter
  pyproject.toml
Labels: Code quality

#4754 [MAINT] Apply repo-review rules
  .pre-commit-config.yaml
Labels: Code quality

#4591 [ENH] make the number of vertices the first dimension of image data
  examples/01_plotting/plot_surf_atlas.py
  examples/02_decoding/plot_haxby_searchlight_surface.py
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/conftest.py
  nilearn/datasets/func.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/decoding/tests/test_space_net.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
  nilearn/maskers/_utils.py
  nilearn/maskers/surface_labels_masker.py
  nilearn/maskers/surface_masker.py
  nilearn/maskers/tests/test_surface_labels_masker.py
  nilearn/maskers/tests/test_surface_masker.py
  nilearn/maskers/tests/test_utils.py
  nilearn/plotting/_utils.py
  nilearn/plotting/displays/_figures.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/regions/rena_clustering.py
  nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
  nilearn/regions/tests/test_parcellations.py
  nilearn/regions/tests/test_rena_clustering.py
  nilearn/reporting/tests/test_glm_reporter.py
  nilearn/surface/surface.py
  nilearn/surface/tests/test_surface.py
Labels: Surface

#4507 [ENH] run GLM on surface data on BIDS datasets
  doc/changes/latest.rst
  nilearn/_utils/data_gen.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
Labels: Surface, Review required

#4794 [MAINT] increase coverage
  .github/workflows/test_with_tox.yml
  README.rst
  nilearn/connectome/tests/test_group_sparse_cov.py
  nilearn/mass_univariate/tests/test_permuted_least_squares.py
  nilearn/tests/test_masking.py
Labels: Review required

#4795 [DOC] move doc string for classes out of constructor
  nilearn/glm/contrasts.py
  nilearn/glm/model.py
  nilearn/glm/regression.py
  nilearn/reporting/html_report.py
Labels: Review required

#4804 [FIX] allow t_r, high_pass, low_pass to be int in signal.clean
  nilearn/signal.py
  nilearn/tests/test_signal.py
Labels: Review required

#4806 [FIX] Allow single 4D nifti as input for SecondLevelModel
  doc/changes/latest.rst
  nilearn/_utils/docs.py
  nilearn/glm/second_level/second_level.py
  nilearn/glm/tests/test_second_level.py
Labels: Review required

#4793 [ENH] revert coercing surface data to 2D
  examples/01_plotting/plot_surf_atlas.py
  examples/01_plotting/plot_surf_stat_map.py
  examples/02_decoding/plot_haxby_searchlight_surface.py
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/datasets/func.py
  nilearn/glm/tests/test_first_level.py
  nilearn/maskers/_utils.py
  nilearn/maskers/surface_labels_masker.py
  nilearn/maskers/tests/test_surface_labels_masker.py
  nilearn/maskers/tests/test_utils.py
  nilearn/plotting/_utils.py
  nilearn/plotting/displays/_figures.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/regions/rena_clustering.py
  nilearn/surface/surface.py
  nilearn/surface/tests/test_surface.py
Labels: Surface, Review required

#4802 [ENH] allow to ignore certain BIDS entities when using query_bids
  examples/07_advanced/plot_beta_series.py
  examples/07_advanced/plot_bids_analysis.py
  examples/07_advanced/plot_surface_bids_analysis.py
  nilearn/glm/first_level/first_level.py
  nilearn/interfaces/bids/query.py
  nilearn/interfaces/tests/test_bids.py
Labels: Blocker, BIDS, Review required

#4715 [ENH] fit second level model on surface
  examples/04_glm_first_level/plot_localizer_surface_analysis.py
  examples/07_advanced/plot_surface_bids_analysis.py
  nilearn/_utils/docs.py
  nilearn/conftest.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/second_level/second_level.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_second_level.py
  nilearn/maskers/_utils.py
  nilearn/maskers/tests/test_surface_masker.py
  nilearn/maskers/tests/test_utils.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/surface/_testing.py
Labels: GLM, Surface
