Repository nilearn/nilearn, pull requests merged in 2024-10, with the labels that each got.

#4555 [FIX] avoid warning when creating int64 images
  doc/changes/latest.rst
  nilearn/plotting/img_plotting.py
  nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
  nilearn/regions/parcellations.py
  nilearn/regions/tests/test_parcellations.py
Labels: Review required

#4578 [STY] run ruff on extra files excluded from previous PR
  nilearn/_utils/docs.py
  nilearn/datasets/neurovault.py
  pyproject.toml
Labels: Review required

#4580 [DOC] add youtube channel in the doc footer
  doc/conf.py
Labels: Review required

#4582 [FIX] `first_level_from_bids` will now return subjects in order
  CITATION.cff
  doc/changes/latest.rst
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
Labels: hacktoberfest-accepted

#4515 [ENH] use BIDS version of the SPM auditory dataset
  examples/00_tutorials/plot_single_subject_single_run.py
  examples/04_glm_first_level/plot_predictions_residuals.py
  nilearn/_utils/helpers.py
  nilearn/datasets/description/spm_auditory.rst
  nilearn/datasets/func.py
  nilearn/datasets/tests/test_func.py
Labels: Review required

#4437 [DOC] Explaining how Decoder works
  doc/changes/latest.rst
  examples/00_tutorials/plot_decoding_tutorial.py
  examples/02_decoding/plot_haxby_understand_decoder.py
Labels: Review required

#4585 [DOC] Demonstrate how to compute & plot functional connectivity for each hemisphere separately with Yeo 17 networks
  doc/changes/latest.rst
  examples/03_connectivity/plot_atlas_comparison.py
Labels: Review required

#4597 [STY] fix ruff pandas error
  nilearn/datasets/tests/test_neurovault.py
  nilearn/glm/first_level/experimental_paradigm.py
  nilearn/glm/tests/test_first_level.py
  nilearn/reporting/glm_reporter.py
  pyproject.toml
Labels: Review required

#4590 [FIX] fix error PTH122 from
  nilearn/datasets/_utils.py
  nilearn/datasets/tests/test_utils.py
  pyproject.toml
Labels: Review required

#4599 [STY] fix simplify ruff errors
  examples/07_advanced/plot_copy_headers_math_img.py
  nilearn/_utils/data_gen.py
  nilearn/_utils/docs.py
  nilearn/_utils/niimg.py
  nilearn/_utils/niimg_conversions.py
  nilearn/_utils/numpy_conversions.py
  nilearn/_utils/tests/test_param_validation.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/decoding/_proximal_operators.py
  nilearn/decoding/decoder.py
  nilearn/decomposition/tests/test_canica.py
  nilearn/decomposition/tests/test_dict_learning.py
  nilearn/experimental/surface/maskers.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_second_level.py
  nilearn/image/tests/_testing.py
  nilearn/image/tests/test_image.py
  nilearn/interfaces/fmriprep/load_confounds_compcor.py
  nilearn/mass_univariate/tests/test_permuted_least_squares.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/surf_plotting.py
  nilearn/regions/tests/test_rena_clustering.py
  pyproject.toml
Labels: Review required

#4598 [STY] fix numpy ruff error
  examples/04_glm_first_level/plot_design_matrix.py
  nilearn/image/tests/test_image.py
  pyproject.toml
Labels: Review required

#4602 [REF] fix ruff 'errors'
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/05_glm_second_level/plot_second_level_one_sample_test.py
  examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
  examples/08_experimental/plot_new_surface_bids_analysis_experimental.py
  maint_tools/check_gha_workflow.py
  maint_tools/show-python-packages-versions.py
  nilearn/__init__.py
  nilearn/_utils/docs.py
  nilearn/_utils/niimg.py
  nilearn/_utils/numpy_conversions.py
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/conftest.py
  nilearn/datasets/atlas.py
  nilearn/datasets/func.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/model.py
  nilearn/glm/tests/test_contrasts.py
  nilearn/interfaces/bids/utils.py
  nilearn/interfaces/tests/test_bids.py
  nilearn/maskers/tests/test_input_data.py
  nilearn/maskers/tests/test_nifti_labels_masker.py
  nilearn/masking.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
  nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py
  nilearn/reporting/glm_reporter.py
  pyproject.toml
Labels: Review required

#4600 [REF] fix refactor 'errors' flagged by ruff
  examples/06_manipulating_images/plot_mask_computation.py
  nilearn/_utils/numpy_conversions.py
  nilearn/_utils/tests/test_param_validation.py
  nilearn/connectome/tests/test_connectivity_matrices.py
  nilearn/datasets/struct.py
  nilearn/decoding/decoder.py
  nilearn/decoding/space_net.py
  nilearn/image/tests/_testing.py
  nilearn/image/tests/test_image.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_surf_plotting.py
  pyproject.toml
Labels: Review required

#4611 [STY] fix fly and up errors flagged by ruff
  examples/02_decoding/plot_miyawaki_reconstruction.py
  examples/03_connectivity/plot_seed_to_voxel_correlation.py
  examples/07_advanced/plot_advanced_decoding_scikit.py
  nilearn/_utils/niimg_conversions.py
  nilearn/_utils/testing.py
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/datasets/func.py
  pyproject.toml
Labels: Review required

#4614 [STY] fixes several PERF error flagged by ruff
  examples/02_decoding/plot_miyawaki_encoding.py
  nilearn/_utils/docs.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/datasets/atlas.py
  nilearn/glm/first_level/first_level.py
  nilearn/interfaces/fmriprep/load_confounds_utils.py
  nilearn/plotting/displays/_slicers.py
  pyproject.toml
Labels: Review required

#4603 [FIX] check type compatibility of GLM mask and input data
  nilearn/_utils/masker_validation.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
Labels: Review required

#4623 [FIX] Fix doc strings for path
  nilearn/_utils/data_gen.py
  nilearn/glm/first_level/first_level.py
  nilearn/interfaces/bids/query.py
Labels: Review required

#4593 [ENH] Add `SurfaceImage.from_volume`
  doc/changes/latest.rst
  examples/08_experimental/plot_3d_map_to_surface_projection_experimental.py
  examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
  examples/08_experimental/plot_new_surface_bids_analysis_experimental.py
  nilearn/experimental/surface/_surface_image.py
  nilearn/experimental/surface/tests/test_surface_image.py
Labels: Review required

#4624 [STY] Fix some naming errors flagged by ruff
  examples/02_decoding/plot_haxby_grid_search.py
  examples/02_decoding/plot_miyawaki_reconstruction.py
  nilearn/interfaces/fmriprep/load_confounds.py
  nilearn/interfaces/fmriprep/load_confounds_components.py
  nilearn/interfaces/fmriprep/load_confounds_utils.py
  nilearn/maskers/tests/test_input_data.py
  pyproject.toml
Labels: Review required

#4205 [ENH] Allow Decoder to work with surface objects
  doc/changes/latest.rst
  examples/08_experimental/plot_surface_image_and_maskers.py
  nilearn/_utils/masker_validation.py
  nilearn/_utils/param_validation.py
  nilearn/decoding/decoder.py
  nilearn/decoding/space_net.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/decoding/tests/test_space_net.py
  nilearn/masking.py
  nilearn/regions/rena_clustering.py
Labels: Surface, Review required

#4631 [MAINT] Replace tempfile in tests with proper pytest fixtures
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/_utils/tests/test_numpy_conversions.py
  nilearn/plotting/tests/test_js_plotting_utils.py
  nilearn/surface/tests/test_surface.py
Labels: Review required

#4627 [STY] Fix ruff errors RUF002-3 and RUF005
  examples/02_decoding/plot_mixed_gambles_frem.py
  examples/02_decoding/plot_miyawaki_encoding.py
  examples/02_decoding/plot_miyawaki_reconstruction.py
  examples/05_glm_second_level/plot_second_level_two_sample_test.py
  examples/07_advanced/plot_age_group_prediction_cross_val.py
  maint_tools/citation_cff_maint.py
  nilearn/_utils/data_gen.py
  nilearn/_utils/niimg_conversions.py
  nilearn/_utils/tests/test_data_gen.py
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/connectome/connectivity_matrices.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/datasets/atlas.py
  nilearn/datasets/func.py
  nilearn/datasets/struct.py
  nilearn/datasets/tests/_testing.py
  nilearn/datasets/tests/test_testing.py
  nilearn/datasets/tests/test_utils.py
  nilearn/decoding/_objective_functions.py
  nilearn/decoding/_proximal_operators.py
  nilearn/decoding/tests/test_objective_functions.py
  nilearn/decoding/tests/test_same_api.py
  nilearn/decomposition/tests/test_canica.py
  nilearn/experimental/conftest.py
  nilearn/experimental/surface/tests/test_maskers.py
  nilearn/glm/first_level/design_matrix.py
  nilearn/glm/tests/test_second_level.py
  nilearn/glm/tests/test_utils.py
  nilearn/image/image.py
  nilearn/image/tests/test_image.py
  nilearn/image/tests/test_resampling.py
  nilearn/maskers/_utils.py
  nilearn/maskers/tests/test_multi_nifti_masker.py
  nilearn/maskers/tests/test_nifti_labels_masker.py
  nilearn/maskers/tests/test_nifti_maps_masker.py
  nilearn/maskers/tests/test_nifti_masker.py
  nilearn/maskers/tests/test_nifti_spheres_masker.py
  nilearn/masking.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/glass_brain.py
  nilearn/regions/signal_extraction.py
  nilearn/regions/tests/test_region_extractor.py
  nilearn/regions/tests/test_signal_extraction.py
  pyproject.toml
Labels: Review required

#3949 [ENH] Improve plotting contours for `PlotlySurfaceFigure` objects by adding `add_contours` method
  doc/changes/latest.rst
  doc/conf.py
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  nilearn/plotting/displays/_figures.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Plotting, Surface, Review required

#4630 Test for screening adjustment
  nilearn/conftest.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/experimental/conftest.py
Labels: Review required

#4589 [ENH] Allow saving SurfaceImage data to Gifti files
  .github/workflows/testing_minimum.yml
  nilearn/experimental/surface/_io.py
  nilearn/experimental/surface/_surface_image.py
  nilearn/experimental/surface/tests/test_surface_image.py
Labels: Review required

#4641 [STY] Fix or silence ARG001-3 error (unused argument)
  doc/conf.py
  doc/sphinxext/gh_substitutions.py
  nilearn/_utils/testing.py
  nilearn/_utils/tests/test_masker_validation.py
  nilearn/conftest.py
  nilearn/connectome/connectivity_matrices.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/connectome/tests/test_group_sparse_cov.py
  nilearn/datasets/_utils.py
  nilearn/datasets/func.py
  nilearn/datasets/neurovault.py
  nilearn/datasets/tests/_testing.py
  nilearn/datasets/tests/test_atlas.py
  nilearn/datasets/tests/test_func.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/datasets/tests/test_testing.py
  nilearn/datasets/tests/test_utils.py
  nilearn/decoding/decoder.py
  nilearn/decoding/space_net_solvers.py
  nilearn/decoding/tests/test_fista.py
  nilearn/decoding/tests/test_graph_net.py
  nilearn/decomposition/_base.py
  nilearn/maskers/multi_nifti_masker.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/masking.py
  nilearn/plotting/displays/_projectors.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/glass_brain.py
  nilearn/plotting/html_document.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/regions/hierarchical_kmeans_clustering.py
  nilearn/regions/region_extractor.py
  nilearn/regions/rena_clustering.py
  nilearn/tests/test_signal.py
  pyproject.toml
Labels: Review required

#4649 [MAINT] remove some unecessary warning filters
  examples/04_glm_first_level/plot_design_matrix.py
  examples/07_advanced/plot_ica_neurovault.py
  nilearn/plotting/matrix_plotting.py
  nilearn/reporting/glm_reporter.py
Labels: Review required

#4644 [STY] fix PLR1704 (redefined-argument-from-local)
  nilearn/datasets/_utils.py
  nilearn/experimental/surface/_datasets.py
  pyproject.toml
Labels: Review required

#4651 [DOC] minor changes to examples for better rendering
  examples/02_decoding/plot_haxby_searchlight_surface.py
  examples/08_experimental/plot_surf_atlas_experimental.py
Labels: Review required

#4643 [STY] fix or silence N802 error related to name of functions (only use lower case)
  nilearn/_utils/segmentation.py
  nilearn/datasets/neurovault.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/decoding/tests/test_objective_functions.py
  nilearn/decoding/tests/test_same_api.py
  nilearn/decoding/tests/test_space_net.py
  nilearn/decomposition/tests/test_multi_pca.py
  nilearn/experimental/surface/tests/test_surface_image.py
  nilearn/glm/model.py
  nilearn/glm/regression.py
  nilearn/glm/tests/test_check_events_file_uses_tab_separators.py
  nilearn/glm/tests/test_contrasts.py
  nilearn/glm/tests/test_dmtx.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_regression.py
  nilearn/glm/tests/test_second_level.py
  nilearn/glm/tests/test_utils.py
  nilearn/image/tests/test_image.py
  nilearn/plotting/html_document.py
  nilearn/plotting/html_stat_map.py
  nilearn/plotting/tests/test_html_stat_map.py
  nilearn/plotting/tests/test_img_plotting/test_plot_anat.py
  nilearn/regions/tests/test_region_extractor.py
  nilearn/regions/tests/test_signal_extraction.py
  nilearn/tests/test_signal.py
  pyproject.toml
Labels: Review required

#4645 [STY] fix ruff error PD011 - use `.to_numpy()` instead of `.values` for pandas dataframe
  examples/00_tutorials/plot_decoding_tutorial.py
  examples/02_decoding/plot_haxby_frem.py
  examples/02_decoding/plot_haxby_glm_decoding.py
  examples/02_decoding/plot_haxby_understand_decoder.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/04_glm_first_level/plot_predictions_residuals.py
  examples/05_glm_second_level/plot_second_level_association_test.py
  examples/07_advanced/plot_advanced_decoding_scikit.py
  examples/07_advanced/plot_localizer_mass_univariate_methods.py
  nilearn/datasets/atlas.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/glm/contrasts.py
  nilearn/glm/first_level/design_matrix.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/second_level/second_level.py
  nilearn/glm/tests/test_dmtx.py
  nilearn/glm/tests/test_second_level.py
  nilearn/image/image.py
  nilearn/interfaces/fmriprep/load_confounds_scrub.py
  nilearn/interfaces/fmriprep/load_confounds_utils.py
  nilearn/interfaces/fmriprep/tests/test_load_confounds.py
  nilearn/reporting/tests/test_reporting.py
  nilearn/signal.py
  pyproject.toml
Labels: Review required

#4653 [MAINT] always run tests in random order
  .github/workflows/README.md
  .github/workflows/detect_test_pollution.yml
  pyproject.toml
  tox.ini
Labels: Review required

#4648 [FIX] Fix several errors (PTH100, PTH103, PTH119, PTH120)
  doc/changes/latest.rst
  doc/conf.py
  doc/sphinxext/github_link.py
  nilearn/datasets/_utils.py
  nilearn/datasets/atlas.py
  nilearn/datasets/func.py
  nilearn/datasets/neurovault.py
  nilearn/datasets/struct.py
  nilearn/datasets/tests/test_func.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/datasets/tests/test_utils.py
  nilearn/glm/first_level/first_level.py
  nilearn/interfaces/bids/query.py
  pyproject.toml
Labels: Review required

#4659 [DOC] Add missing default values to the docstrings in 'nilearn/glm' - part 2
  doc/changes/latest.rst
  nilearn/glm/first_level/design_matrix.py
  nilearn/glm/first_level/first_level.py
  nilearn/glm/first_level/hemodynamic_models.py
Labels: Review required

#4660 [DOC] Add missing default values to the docstrings in 'nilearn/plotting'
  doc/changes/latest.rst
  nilearn/plotting/find_cuts.py
  nilearn/plotting/html_connectome.py
  nilearn/plotting/html_stat_map.py
  nilearn/plotting/html_surface.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/surf_plotting.py
Labels: Review required

#4666 [FIX] Warn if smoothing_fwhm parameter passed to FLM for surface data
  nilearn/glm/first_level/first_level.py
  nilearn/glm/tests/test_first_level.py
Labels: Review required

#4655 [MAINT] minor fixes on maintenance scripts
  maint_tools/check_glossary_term.py
  maint_tools/show-python-packages-versions.py
Labels: Review required

#4670 [STY] fix SIM117 error
  nilearn/datasets/_utils.py
  nilearn/datasets/tests/test_testing.py
  pyproject.toml
Labels: Review required

#4671 [FIX] Fix several errors (PTH101, PTH102, PTH107, PTH110, PTH111, PTH113, PTH201) in `nilearn.datasets` package
  nilearn/datasets/_utils.py
  nilearn/datasets/atlas.py
  nilearn/datasets/func.py
  nilearn/datasets/neurovault.py
  nilearn/datasets/tests/test_atlas.py
  nilearn/datasets/tests/test_func.py
  nilearn/datasets/tests/test_mocking_autoused.py
  nilearn/datasets/tests/test_neurovault.py
  nilearn/datasets/tests/test_testing.py
  nilearn/datasets/tests/test_utils.py
  nilearn/datasets/utils.py
  pyproject.toml
Labels: Review required

#4650 [DOC][MAINT] build doc with minimum version of python and dependencies
  .github/workflows/README.md
  .github/workflows/build-docs.yml
  .github/workflows/release-docs.yml
  .gitignore
  CONTRIBUTING.rst
  doc/Makefile
  doc/maintenance.rst
  examples/02_decoding/plot_haxby_different_estimators.py
  examples/02_decoding/plot_haxby_full_analysis.py
  examples/03_connectivity/plot_compare_decomposition.py
  examples/03_connectivity/plot_group_level_connectivity.py
  examples/03_connectivity/plot_seed_to_voxel_correlation.py
  examples/03_connectivity/plot_sphere_based_connectome.py
  examples/04_glm_first_level/plot_design_matrix.py
  examples/04_glm_first_level/plot_predictions_residuals.py
  examples/05_glm_second_level/plot_second_level_design_matrix.py
  examples/05_glm_second_level/plot_second_level_two_sample_test.py
  examples/07_advanced/plot_age_group_prediction_cross_val.py
  nilearn/_utils/logger.py
  tox.ini
Labels: Review required

#4682 [DOC] use new surface API in plot_surface_bids_analysis
  examples/07_advanced/plot_surface_bids_analysis.py
  examples/08_experimental/plot_new_surface_bids_analysis_experimental.py
Labels: Documentation, Surface, Review required

#4681 [DOC] use new surface API in plot_localizer_surface_analysis
  examples/04_glm_first_level/plot_localizer_surface_analysis.py
  examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
Labels: Documentation, Surface, Review required

#4683 [DOC] use new surface API in plot_surf_stat_map
  examples/01_plotting/plot_surf_stat_map.py
  examples/08_experimental/plot_surf_stat_map_experimental.py
Labels: Documentation, Surface, Review required

#4657 [TEST] Clean surface fixtures
  nilearn/conftest.py
  nilearn/decoding/tests/test_decoder.py
  nilearn/decoding/tests/test_space_net.py
  nilearn/experimental/conftest.py
  nilearn/experimental/plotting/tests/test_surface_plotting.py
  nilearn/experimental/reporting/tests/test_html_report.py
  nilearn/experimental/surface/tests/test_io.py
  nilearn/experimental/surface/tests/test_maskers.py
  nilearn/experimental/surface/tests/test_surface_image.py
  nilearn/glm/tests/test_first_level.py
  nilearn/reporting/tests/test_glm_reporter.py
Labels: Surface, Review required

#4675 [FIX] Silence B018 errors
  nilearn/glm/contrasts.py
  nilearn/glm/first_level/design_matrix.py
  nilearn/glm/tests/test_contrasts.py
  nilearn/reporting/tests/test_reporting.py
  pyproject.toml
Labels: Review required

#4629 [MAINT] speed up some tests for first level GLM and interface/bids
  nilearn/_utils/tests/test_niimg_conversions.py
  nilearn/conftest.py
  nilearn/glm/tests/test_first_level.py
  nilearn/glm/tests/test_second_level.py
  nilearn/image/tests/test_image.py
  nilearn/interfaces/tests/test_bids.py
  nilearn/maskers/tests/test_multi_nifti_masker.py
Labels: Review required

#4500 [ENH] add a function to help reporting post-masking atlas in LabelsMaskers
  nilearn/maskers/nifti_labels_masker.py
Labels: Review required

#4674 [DOC] use new surface API in plot_3d_map_to_surface_projection
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  examples/08_experimental/plot_3d_map_to_surface_projection_experimental.py
Labels: Documentation, Blocker, Surface

#4688 [ENH] move experimental surface plotting into the stable API
  doc/Makefile
  doc/changes/latest.rst
  nilearn/experimental/plotting/_surface_plotting.py
  nilearn/experimental/plotting/tests/test_surface_plotting.py
  nilearn/plotting/_utils.py
  nilearn/plotting/html_surface.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_surf_plotting.py
Labels: Plotting, Blocker, Surface

#4685 [MAINT] move surface IO module to stable surface API
  nilearn/_utils/tests/test_common.py
  nilearn/conftest.py
  nilearn/experimental/surface/_datasets.py
  nilearn/experimental/surface/_io.py
  nilearn/experimental/surface/_surface_image.py
  nilearn/experimental/surface/tests/test_io.py
  nilearn/surface/surface.py
  nilearn/surface/tests/test_surface.py
Labels: Surface

#4678 [DOC] use new surface API in plot_surf_atlas
  doc/modules/experimental.rst
  doc/visual_testing/reporter_visual_inspection_suite.py
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  examples/01_plotting/plot_surf_atlas.py
  examples/08_experimental/plot_surf_atlas_experimental.py
  examples/08_experimental/plot_surface_image_and_maskers.py
  nilearn/experimental/surface/__init__.py
  nilearn/experimental/surface/_datasets.py
  nilearn/experimental/surface/tests/test_datasets.py
Labels: Documentation, Blocker, Surface, Review required
