Repository nilearn/nilearn, pull requests merged in 2025-01, with the labels that each got.

#4984 [REF] extract check doc build type
  .github/workflows/build-docs.yml
Labels: Review required

#5006 [FIX] convert labels to string in labels in dataset fetchers
  doc/visual_testing/reporter_visual_inspection_suite.py
  examples/01_plotting/plot_3d_map_to_surface_projection.py
  examples/01_plotting/plot_surf_atlas.py
  examples/01_plotting/plot_surf_stat_map.py
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/datasets/atlas.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/tests/test_nifti_labels_masker.py
Labels: Blocker, Review required

#5013 [FIX] Convert Schaeffer atlas labels to list of strings
  doc/visual_testing/reporter_visual_inspection_suite.py
  nilearn/datasets/atlas.py
  nilearn/datasets/tests/test_atlas.py
Labels: Review required

#5017 [FIX] build examples in PR
  .github/workflows/build-docs.yml
  .gitignore
  build_tools/github/build_type.sh
  build_tools/github/merge_upstream.sh
  examples/02_decoding/plot_haxby_full_analysis.py
Labels: Review required

#5005 [STY] add mising stacklevel in warnings in in nilearn.image
  nilearn/image/image.py
  nilearn/image/resampling.py
  pyproject.toml
Labels: Review required

#5015 [DOC] refactor description datasets functional derivatives
  examples/01_plotting/plot_visualize_megatrawls_netmats.py
  examples/02_decoding/plot_mixed_gambles_frem.py
  examples/02_decoding/plot_oasis_vbm.py
  examples/02_decoding/plot_oasis_vbm_space_net.py
  examples/05_glm_second_level/plot_oasis.py
  nilearn/datasets/description/Megatrawls.rst
  nilearn/datasets/description/mixed_gambles.rst
  nilearn/datasets/description/oasis1.rst
  nilearn/datasets/func.py
  nilearn/datasets/struct.py
Labels: Review required

#5021 [DOC] update colormaps and doc strings
  nilearn/maskers/nifti_masker.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/html_connectome.py
  nilearn/plotting/html_stat_map.py
  nilearn/plotting/html_surface.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/surf_plotting.py
Labels: Review required

#5026 [MAINT] update badges
  README.rst
Labels: Review required

#5023 [MISC] update doc strings types
  nilearn/_utils/docs.py
  nilearn/_utils/niimg.py
  nilearn/_utils/niimg_conversions.py
  nilearn/connectome/group_sparse_cov.py
  nilearn/image/image.py
  nilearn/image/resampling.py
  nilearn/interfaces/bids/glm.py
  nilearn/interfaces/fmriprep/load_confounds_strategy.py
  nilearn/maskers/multi_nifti_labels_masker.py
  nilearn/maskers/multi_nifti_maps_masker.py
  nilearn/maskers/multi_nifti_masker.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/masking.py
Labels: Review required

#4820 [ENH] Standardize atlases: add look up tables for deterministic atlases
  doc/changes/latest.rst
  nilearn/_utils/tests/test_common.py
  nilearn/conftest.py
  nilearn/datasets/atlas.py
  nilearn/datasets/tests/test_atlas.py
Labels: Review required

#5019 [DOC] update documentation for look up tables of atlases
  CONTRIBUTING.rst
  nilearn/_utils/docs.py
  nilearn/datasets/atlas.py
Labels: Review required

#5033 [DOC] add links to more older doc versions
  doc/versions.rst
Labels: Review required

#5022 [MAINT] pacify mypy
  nilearn/__init__.py
  nilearn/_utils/docs.py
  nilearn/_utils/testing.py
  nilearn/conftest.py
  nilearn/glm/first_level/first_level.py
  nilearn/plotting/cm.py
  nilearn/plotting/displays/_projectors.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/html_document.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/surf_plotting.py
  pyproject.toml
Labels: Review required

#5014 [DOC] refactor description templates
  examples/00_tutorials/plot_single_subject_single_run.py
  nilearn/_utils/docs.py
  nilearn/datasets/description/fsaverage.rst
  nilearn/datasets/description/fsaverage3.rst
  nilearn/datasets/description/fsaverage4.rst
  nilearn/datasets/description/fsaverage5.rst
  nilearn/datasets/description/fsaverage6.rst
  nilearn/datasets/description/fsaverage_content.rst
  nilearn/datasets/description/icbm152_2009.rst
  nilearn/datasets/struct.py
Labels: Review required

#5038 [MAINT] remove dead code
  .github/workflows/test_with_tox.yml
  nilearn/_utils/tests/test_common.py
  nilearn/datasets/tests/test_func.py
  nilearn/glm/tests/_testing.py
  nilearn/glm/tests/test_hemodynamic_models.py
  nilearn/plotting/displays/_axes.py
  nilearn/plotting/tests/test_img_plotting/test_plot_connectome.py
  nilearn/reporting/utils.py
Labels: Review required

#5037 [MAINT] Make functions used outside of their module public
  nilearn/_utils/__init__.py
  nilearn/_utils/cache_mixin.py
  nilearn/_utils/helpers.py
  nilearn/_utils/masker_validation.py
  nilearn/_utils/tests/test_cache_mixin.py
  nilearn/_utils/tests/test_common.py
  nilearn/_utils/tests/test_helpers.py
  nilearn/decoding/decoder.py
  nilearn/decoding/searchlight.py
  nilearn/decomposition/dict_learning.py
  nilearn/glm/second_level/second_level.py
  nilearn/image/image.py
  nilearn/interfaces/bids/glm.py
  nilearn/maskers/base_masker.py
  nilearn/maskers/multi_nifti_masker.py
  nilearn/maskers/nifti_labels_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/nifti_masker.py
  nilearn/maskers/nifti_spheres_masker.py
  nilearn/maskers/surface_labels_masker.py
  nilearn/maskers/surface_masker.py
  nilearn/maskers/tests/test_base_masker.py
  nilearn/maskers/tests/test_input_data.py
  nilearn/maskers/tests/test_nifti_masker.py
  nilearn/masking.py
  nilearn/plotting/__init__.py
  nilearn/plotting/displays/_projectors.py
  nilearn/plotting/displays/_slicers.py
  nilearn/plotting/img_plotting.py
  nilearn/plotting/matrix_plotting.py
  nilearn/plotting/surf_plotting.py
  nilearn/plotting/tests/test_matrix_plotting.py
  nilearn/regions/parcellations.py
  nilearn/regions/rena_clustering.py
  nilearn/regions/tests/test_rena_clustering.py
  nilearn/reporting/__init__.py
  nilearn/reporting/glm_reporter.py
  nilearn/reporting/html_report.py
Labels: Review required

#5032 [MAINT] Add docstrings to test mass_univariate
  nilearn/mass_univariate/tests/test_permuted_least_squares.py
  nilearn/mass_univariate/tests/test_utils.py
  pyproject.toml
Labels: Review required

#5031 [DOC] update description nki
  examples/01_plotting/plot_surf_stat_map.py
  examples/07_advanced/plot_surface_image_and_maskers.py
  nilearn/datasets/description/nki_enhanced_surface.rst
  nilearn/datasets/func.py
Labels: Review required

#5027 [REF] refactor tests nifti maps masker
  nilearn/conftest.py
  nilearn/maskers/tests/conftest.py
  nilearn/maskers/tests/test_multi_nifti_maps_masker.py
  nilearn/maskers/tests/test_nifti_labels_masker.py
  nilearn/maskers/tests/test_nifti_maps_masker.py
  nilearn/reporting/tests/test_html_report.py
  pyproject.toml
Labels: Review required

#5041 [REF] refactor atlas
  doc/changes/latest.rst
  doc/visual_testing/reporter_visual_inspection_suite.py
  nilearn/_utils/docs.py
  nilearn/_utils/tests/test_common.py
  nilearn/datasets/atlas.py
  nilearn/datasets/tests/test_atlas.py
Labels: Review required

#4917 [MAINT] (Multi)NiftiMapsMasker: comply with check_parameters_default_constructible
  nilearn/_utils/class_inspect.py
  nilearn/conftest.py
  nilearn/maskers/multi_nifti_maps_masker.py
  nilearn/maskers/nifti_maps_masker.py
  nilearn/maskers/tests/test_multi_nifti_maps_masker.py
  nilearn/maskers/tests/test_nifti_maps_masker.py
  nilearn/regions/region_extractor.py
  nilearn/regions/tests/test_region_extractor.py
Labels: Blocker

#4968 [ENH] Add reports for SurfaceMapsMasker
  doc/changes/latest.rst
  doc/modules/generated_reports/masker_reports_examples.rst
  doc/visual_testing/reporter_visual_inspection_suite.py
  nilearn/conftest.py
  nilearn/maskers/surface_maps_masker.py
  nilearn/maskers/tests/test_surface_maps_masker.py
  nilearn/plotting/html_surface.py
  nilearn/plotting/tests/conftest.py
  nilearn/plotting/tests/test_html_surface.py
  nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py
  nilearn/plotting/tests/test_img_plotting/test_plot_glass_brain.py
  nilearn/plotting/tests/test_img_plotting/test_plot_img.py
  nilearn/plotting/tests/test_img_plotting/test_plot_img_comparisons.py
  nilearn/plotting/tests/test_img_plotting/test_plot_markers.py
  nilearn/plotting/tests/test_img_plotting/test_plot_prob_atlas.py
  nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
  nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py
  nilearn/plotting/tests/test_surf_plotting.py
  nilearn/reporting/data/html/partials/figure.html
  nilearn/reporting/data/html/report_body_template_surfacemapsmasker.html
  nilearn/reporting/html_report.py
Labels: Review required
